### ISSUE TITLE
String can't be translated

### ISSUE THREAD

**Issue by 0xGabrielel** [Extremelyd1/Strat-Roulette#38]
String should be added to the newest translation files

**Comment by 0xGabrielel** [comment]
https://github.com/Extremelyd1/Strat-Roulette/blob/001f985bb8850134f9674f872ade1912ea0d4741/stratroulette/timers.sp#L415

**Comment by Extremelyd1** [comment]
Addressed in a45918f2270c824924876495459ebeb0a2cbf15f.
