### ISSUE TITLE
errors_20191125.log

### ISSUE THREAD

**Issue by legendksk** [Extremelyd1/Strat-Roulette#44]
L 11/25/2019 - 17:46:40: [SM] Blaming: stratroulette.smx
L 11/25/2019 - 17:46:40: [SM] Call stack trace:
L 11/25/2019 - 17:46:40: [SM]   [0] GetClientName
L 11/25/2019 - 17:46:40: [SM]   [1] Line 70, stratroulette/round-modifiers/kill-list.sp::SetTopList
L 11/25/2019 - 17:46:40: [SM]   [2] Line 8, stratroulette/round-modifiers/kill-list.sp::ConfigureKillList
L 11/25/2019 - 17:46:40: [SM]   [3] Line 399, stratroulette/readfile.sp::ReadNewRound
L 11/25/2019 - 17:46:40: [SM]   [4] Line 13, stratroulette/events.sp::RoundStartEvent
L 11/25/2019 - 18:18:30: Error log file session closed.

help pls

**Comment by legendksk** [comment]
L 11/26/2019 - 05:02:34: [SM] Blaming: stratroulette.smx
L 11/26/2019 - 05:02:34: [SM] Call stack trace:
L 11/26/2019 - 05:02:34: [SM]   [0] ArrayList.Get
L 11/26/2019 - 05:02:34: [SM]   [1] Line 67, stratroulette/round-modifiers/hot-potato.sp::SelectHotPotato
L 11/26/2019 - 05:02:34: [SM]   [2] Line 45, stratroulette/round-modifiers/hot-potato.sp::NewHotPotatoTimer

**Comment by legendksk** [comment]
L 11/26/2019 - 07:17:53: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/26/2019 - 07:17:53: [SM] Blaming: stratroulette.smx
L 11/26/2019 - 07:17:53: [SM] Call stack trace:
L 11/26/2019 - 07:17:53: [SM]   [0] GetEntProp
L 11/26/2019 - 07:17:53: [SM]   [1] Line 35, stratroulette/round-modifiers/all-or-nothing.sp::AllOrNothingOnPlayerRunCmd
L 11/26/2019 - 07:17:53: [SM]   [2] Line 374, ..\stratroulette.sp::OnPlayerRunCmd
L 11/26/2019 - 07:23:08: Error log file session closed.

**Comment by Extremelyd1** [comment]
I believe the first and second errors are due to the fact that there are not enough players, therefore it can't pick a player for the kill list. These should be fixed once I implement the minimum number of required players for a round (#33).
The last error should be fixed in 34fe6f2a8179632dd79a233159441d2b3e76db2c.
