### ISSUE TITLE
Round Buddy System Bug

### ISSUE THREAD

**Issue by legendksk** [Extremelyd1/Strat-Roulette#47]
```
	"37"
	{
		"name"			"RoundBuddySystemName"
		"description"	"RoundBuddySystemDesc"
		"weapon"		"weapon_primary_random;weapon_secondary_random"
		"buddysystem"	"1"
	}
```

when he shoots his teammate's chicken
round does not end

**Comment by Extremelyd1** [comment]
Do you have any stack trace of an error, or was there no error and the round simply did not end?

**Comment by legendksk** [comment]
no error log
round does not end when he shoots his teammate's chicken
