### ISSUE TITLE
Strat-Roulette errors logs

### ISSUE THREAD

**Issue by legendksk** [Extremelyd1/Strat-Roulette#49]
hi;
logs/errors_20200331.log

L 03/31/2020 - 14:09:28: [SM] Call stack trace:
L 03/31/2020 - 14:09:28: [SM]   [0] AcceptEntityInput
L 03/31/2020 - 14:09:28: [SM]   [1] Line 71, stratroulette/round-modifiers/clone.sp::CloneLookAtWeaponListener
L 03/31/2020 - 14:09:54: [SM] Exception reported: Entity 235 (235) is invalid
L 03/31/2020 - 14:09:54: [SM] Blaming: stratroulette.smx
L 03/31/2020 - 14:09:54: [SM] Call stack trace:
L 03/31/2020 - 14:09:54: [SM]   [0] SetEntPropEnt
L 03/31/2020 - 14:09:54: [SM]   [1] Line 89, stratroulette/round-modifiers/clone.sp::GiveCloneWeapon
L 03/31/2020 - 14:09:54: [SM]   [2] Line 79, stratroulette/round-modifiers/clone.sp::DelayCloneWeaponTimer
L 03/31/2020 - 14:12:29: [SM] Exception reported: Entity -1 (-1) is invalid
L 03/31/2020 - 14:12:29: [SM] Blaming: stratroulette.smx
L 03/31/2020 - 14:12:29: [SM] Call stack trace:
L 03/31/2020 - 14:12:29: [SM]   [0] SetEntProp
L 03/31/2020 - 14:12:29: [SM]   [1] Line 367, stratroulette/util.sp::SetClipAmmo
L 03/31/2020 - 14:12:29: [SM]   [2] Line 47, stratroulette/round-modifiers/shared-ammo.sp::SharedAmmoWeaponFireEvent
L 03/31/2020 - 14:12:29: [SM] Exception reported: Entity -1 (-1) is invalid
L 03/31/2020 - 14:12:29: [SM] Blaming: stratroulette.smx

**Comment by legendksk** [comment]
L 03/31/2020 - 14:16:55: [SM] Call stack trace:
L 03/31/2020 - 14:16:55: [SM]   [0] SetEntPropEnt
L 03/31/2020 - 14:16:55: [SM]   [1] Line 89, stratroulette/round-modifiers/clone.sp::GiveCloneWeapon
L 03/31/2020 - 14:16:55: [SM]   [2] Line 79, stratroulette/round-modifiers/clone.sp::DelayCloneWeaponTimer
L 03/31/2020 - 14:30:59: [SM] Exception reported: Property "m_hActiveWeapon" not found (entity 0/worldspawn)
L 03/31/2020 - 14:30:59: [SM] Blaming: stratroulette.smx
L 03/31/2020 - 14:30:59: [SM] Call stack trace:
L 03/31/2020 - 14:30:59: [SM]   [0] GetEntPropEnt
L 03/31/2020 - 14:30:59: [SM]   [1] Line 27, stratroulette/round-modifiers/stun-gun.sp::StunGunPlayerOnTakeDamageHook
L 03/31/2020 - 14:39:51: Error log file session closed.

**Comment by jvpoppel** [comment]
@legendksk Could you add more details on what you expected to happen, which rounds, et cetera?

**Comment by Extremelyd1** [comment]
I'm closing this for now
