### ISSUE TITLE
Pure Server file tunnel vision

### ISSUE THREAD

**Issue by piotrdylag** [Extremelyd1/Strat-Roulette#50]
**Describe the bug**
There is a problem cause, when we choose tunnel vision, we don't have any tunnel look and in console I have this error: Pure server: file: GAME\materials/overlays/stratroulette/tunnel_vision_overlay.vmt ( 1 104 68 ) could not open file to hash : 195c92bf5bfa444e686c61e8e52241eb 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jvpoppel** [comment]
@piotrdylag Could you add more details on how you set up your server et cetera?

**Comment by Extremelyd1** [comment]
Have you copied the tunnel_vision_overlay.vmt to the server and to your fast DL server? If not, that might be the issue. Otherwise, it might be a bug from CSGO with the pure server files that cannot get verified. If that is the case, there is nothing I can do.

**Comment by Extremelyd1** [comment]
I'm closing this for now.
